### ISSUE TITLE
개발자 퇴근 후 페어 프로그래밍

### ISSUE THREAD

**Issue by ghojeong** [nathankim0/nathankim0#1]
오후 6시부터 1시간 정도 페어 프로그래밍 시간을 갖는다.

페어 프로그래밍의 주제는 다양하다. 본인이 구현하고 싶지만 잘 안되는 것에 대한 도움을 요청하는 것도 가능하다.

만약 하고 싶은 주제가 없다면, 디폴트로 알고리즘 문제 풀이 페어 프로그래밍을 한다.

페어 프로그래밍은 다음과 같이 이루어진다.

- driver
    - 뇌를 비우고 키보드를 두들겨서 타이핑을 하는 역할을 한다. 
    - 인터넷 검색도 하지 못한다. 대신 무엇을 검색해달라고 navigator 에게 부탁할 수는 있다.
    - 타이핑을 하다가 생기는 모든 궁금증은 (꼭 문제와 관련되지 않더라도), navigator 에게 질문할 수 있다.
- navigator
    - 알고리즘 문제를 설명한다.
    - 문제를 풀기 위해 적어야할 내용을 driver 에게 알려준다.
    - 혹시라도 driver 가 질문을 한다면, 인터넷 검색을 해서라도 답변을 해주어야 한다.

driver 와 navigator 를 번갈아 가면서 하기 위해, 매일 문제를 2개 이상 푸는것을 권장한다.

**Comment by ghojeong** [comment]
# [파이썬 알고리즘 인터뷰](https://book.naver.com/bookdb/book_detail.naver?bid=16406247)

**Comment by nathankim0** [comment]
ㅋㅋ 이거 까먹고있었당

**Comment by ghojeong** [comment]
제가 원하는 스터디 문화가 자리잡히는것 같아서 이슈 닫겠습니다.
